### ISSUE TITLE
Nintedont Config Update

### ISSUE THREAD

**Issue by KBan999** [piratesephiroth/TeconmoonWiiVCInjector#1]
I have been trying to use my gamepad on the forwarders i made but it doesn't register inputs. I think the new configs from the latest nintendont build can help out with the small issue., it is under "Wii U gamepad port". Many thanks!

**Comment by piratesephiroth** [comment]
ok, I'll take a look

**Comment by piratesephiroth** [comment]
Option added. I just have to fix a few more things and I'll make a new release
