### ISSUE TITLE
Nintendont langage

### ISSUE THREAD

**Issue by WilliamVercken** [piratesephiroth/TeconmoonWiiVCInjector#16]
Hi!

I used the 3.0.12.0 version to generate nincfg.bin file on my SD card, and the only option I selected was the french langage.
But when I loaded TimeSplitters 2 on my Wii U, the game was in spanish.

So I used another program (NinCFGEditor : https://github.com/libertyernie/NinCFGEditor) to see if the problem was from the console or something else, and it worked, the game is now in french. So, I think there is a problem with the nincfg.bin file generator of TeconMoon's WiiVC Injector.

Thank you!

**Comment by piratesephiroth** [comment]
fixed
