### ISSUE TITLE
Unhandled exception - Microsoft.WindowsAPICodePack.Shell

### ISSUE THREAD

**Issue by Tachi107** [piratesephiroth/TeconmoonWiiVCInjector#18]
Sorry for the Italian error messages. dotnet 4.8 should be already installed.

![image](https://user-images.githubusercontent.com/34214253/182031603-82430e09-e832-4496-8fe2-d9b835b40b29.png)

**Comment by nchudson** [comment]
[Version 3.0.11.0](https://github.com/piratesephiroth/TeconmoonWiiVCInjector/releases/tag/3.0.11) does not appear to have this error. I ran across the same issue you're seeing and that fixed it for me.

**Comment by OoIceDeepoO** [comment]
![Capture40](https://user-images.githubusercontent.com/56861250/183277783-4df45371-9721-45ad-b270-82bb8197f5eb.JPG)

Here is the error in English

**Comment by piratesephiroth** [comment]
All right, This should have been fixed now in the latest release.

**Comment by Tachi107** [comment]
Unfortunately I'll won't be able to check if this was fixed for me, but the others are welcome to do it of course :)
